- hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: install Nginx
      yum:
        name: nginx
      notify:
        - reload nginx

    - name: Ensure nginx is started and enabled to start at boot.
      service: name=nginx state=started enabled=yes

    - name: yum update
      yum:
        name: '*'
        state: latest

    - name: enable Nginx
      systemd:
        name: nginx
        enabled: yes